{% set version = "0.1.3" %}

package:
  name: qvalue
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/q/qvalue/qvalue-{{ version }}.tar.gz
  sha256: 9b0a5de3ec07270ca0a36fb18f18ccef2b1f438eda28a630e76e2754f17f5b29
  patches:
    - 0001-use-numpy-import.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ={{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - qvalue
  commands:
    - pip check
  requires:
    - pip
    - python ={{ python_min }}

about:
  home: https://github.com/nfusi/qvalue
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Converts p-values in q-values, see (Storey and Tibshirani, 2003)

extra:
  recipe-maintainers:
    - danielnachun
